# Production Docker Compose
version: '3.8'

services:
  plinko-app:
    image: plinko-game:latest
    container_name: plinko-production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - TON_NETWORK=mainnet
      - TONAPI_KEY=${TONAPI_KEY}
      - TONCENTER_API_KEY=${TONCENTER_API_KEY}
      - GAME_WALLET_MNEMONIC=${GAME_WALLET_MNEMONIC}
      - GAME_WALLET_ADDRESS=${GAME_WALLET_ADDRESS}
      - JWT_SECRET=${JWT_SECRET}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - LOG_LEVEL=info
      - ENABLE_REQUEST_LOGGING=true
      - ENABLE_TRANSACTION_LOGGING=true
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    external: true
    name: plinko-network